/**
 * Veltrix CRM - Automated Lead Ingest Simulation Executor
 * 
 * This Node.js script demonstrates how an external scraper can stream company/contact
 * records directly to the Veltrix ingestion endpoint via authenticated HTTP POST.
 * 
 * Usage:
 *   1. Ensure the Veltrix Next.js dev server is running (usually http://localhost:3000)
 *   2. Set the environment variable SCRAPER_SECRET_KEY in your server's .env.local
 *   3. Run this script: node scripts/simulate_scraper.js
 */

const SCRAPER_SECRET_KEY = process.env.SCRAPER_SECRET_KEY || 'super-secret-scraper-key';
const API_URL = process.env.VELTRIX_API_URL || 'http://localhost:3000/api/leads/ingest';

// Sample leads generated by a scraper run
const payload = {
  pool_name: 'Live Scraper Stream (Midwest Logistics)',
  leads: [
    {
      companyName: 'Stoic Growth Corp',
      email: 'marcus.aurelius@stoicgrowth.io',
      contactName: 'Marcus Aurelius',
      jobTitle: 'VP of Sales & Strategy',
      industry: 'Logistics Technology'
    },
    {
      companyName: 'NanoFlow Automation',
      email: 'schen@nanoflow.tech',
      contactName: 'Sarah Chen',
      jobTitle: 'Director of Procurement',
      industry: 'Industrial Robotics'
    },
    {
      companyName: 'Apex Supply Chain Solutions',
      email: 'd.vance@apexlogistics.com',
      contactName: 'David Vance',
      jobTitle: 'Head of Global Operations',
      industry: 'Transportation & Logistics'
    },
    {
      companyName: 'Midwest Freight Hub',
      email: 'dispatch@midwestfreight.org',
      contactName: 'Clarissa Harlowe',
      jobTitle: 'Operations Manager',
      industry: 'Logistics Infrastructure Midwest'
    },
    {
      companyName: 'Steelcraft Assembly Systems',
      email: 'k.kovacs@steelcraftsystems.com',
      contactName: 'Karel Kovacs',
      jobTitle: 'Production Lead',
      industry: 'Automation Systems'
    }
  ]
};

async function executeIngest() {
  console.log(`[Scraper Simulator] Directing lead stream to: ${API_URL}`);
  console.log(`[Scraper Simulator] Ingesting ${payload.leads.length} records...`);

  try {
    const response = await fetch(`${API_URL}?api_key=${SCRAPER_SECRET_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
    });

    const data = await response.json();

    if (response.ok) {
      console.log('\n[Scraper Simulator] SUCCESS! Leads ingested and upserted in Supabase.');
      console.log(`[Scraper Simulator] Database upsert count: ${data.count}`);
      console.log('[Scraper Simulator] Returned rows summary:');
      data.leads.forEach((l) => {
        console.log(`  - [${l.status}] ${l.contact_name} (${l.contact_email}) @ ${l.company_name}`);
      });
    } else {
      console.error('\n[Scraper Simulator] FAILED! Server returned error response:');
      console.error(`Status: ${response.status} ${response.statusText}`);
      console.error(data);
    }
  } catch (error) {
    console.error('\n[Scraper Simulator] EXCEPTION! Failed to connect to Next.js API route:');
    console.error(error.message);
    console.log('\nTip: Make sure your Next.js local server is running and accessible.');
  }
}

// Run the ingestion stream
executeIngest();
